## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
import numpy as np

list_ = ['1','2','3','4','5']
print(f'Datatype of list_:{type(list_)}')

array_list = np.array(object= list_)
print(f'Array list are: {array_list}')
print(f'Datatype of array_list: {type(array_list)}')

Datatype of list_:<class 'list'>
Array list are: ['1' '2' '3' '4' '5']
Datatype of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.



In [16]:
import numpy as np

list_ = ['1','2','3','4','5']
print(type(list_))

for i in list_:
    print(f'Datatype of {i} is {type(i)}')
    
print('*************************************')
array_list = np.array(object = list_)
for k in array_list:
    print(f'Datatype of {k} is {type(k)}')

<class 'list'>
Datatype of 1 is <class 'str'>
Datatype of 2 is <class 'str'>
Datatype of 3 is <class 'str'>
Datatype of 4 is <class 'str'>
Datatype of 5 is <class 'str'>
*************************************
Datatype of 1 is <class 'numpy.str_'>
Datatype of 2 is <class 'numpy.str_'>
Datatype of 3 is <class 'numpy.str_'>
Datatype of 4 is <class 'numpy.str_'>
Datatype of 5 is <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


In [14]:
import numpy as np

list_ = np.array(['1','2','3','4','5'])
print(f'The datatype of {list_} is {list_.dtype}')
array_list = np.array(object = list_, dtype=int)
print(array_list)
print(f'The datatype of {array_list} is {array_list.dtype}')

The datatype of ['1' '2' '3' '4' '5'] is <U1
[1 2 3 4 5]
The datatype of [1 2 3 4 5] is int64


In [12]:
for j in list_:
    print(f'The datatype of {j} is {type(j)}')
print('#########################################')
for k in array_list:
    print(f'The datatype of {k} is {type(k)}')

The datatype of 1 is <class 'numpy.str_'>
The datatype of 2 is <class 'numpy.str_'>
The datatype of 3 is <class 'numpy.str_'>
The datatype of 4 is <class 'numpy.str_'>
The datatype of 5 is <class 'numpy.str_'>
#########################################
The datatype of 1 is <class 'numpy.int64'>
The datatype of 2 is <class 'numpy.int64'>
The datatype of 3 is <class 'numpy.int64'>
The datatype of 4 is <class 'numpy.int64'>
The datatype of 5 is <class 'numpy.int64'>


## Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [24]:
import numpy as np

num_list = [[1,2,3],[4,5,6]]  # variable

num_array = np.array(object=num_list) # array
print(num_array)

print(f'Shape and size of {num_list} are {type(num_list)} and {len(num_list)} ')
print()
print(f'Shape and size of \n{num_array} are {num_array.shape} and {num_array.size}')

[[1 2 3]
 [4 5 6]]
Shape and size of [[1, 2, 3], [4, 5, 6]] are <class 'list'> and 2 

Shape and size of 
[[1 2 3]
 [4 5 6]] are (2, 3) and 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

## [Hint: The size of the array will be 9 and the shape will be (3,3).

In [40]:
import numpy as np

arr = np.zeros(9, dtype=int).reshape((3,3))
print(arr)
print()
print(f'The size of \n{arr} will be {arr.size}')
print()
print(f'The shape of \n{arr} is {arr.shape}')

[[0 0 0]
 [0 0 0]
 [0 0 0]]

The size of 
[[0 0 0]
 [0 0 0]
 [0 0 0]] will be 9

The shape of 
[[0 0 0]
 [0 0 0]
 [0 0 0]] is (3, 3)


In [41]:
arr1=np.random.randint(0,1,(3,3))
print(arr1)
print()
print(f'The size of \n{arr1} will be {arr1.size}')
print()
print(f'The shape of \n{arr1} is {arr1.shape}')


[[0 0 0]
 [0 0 0]
 [0 0 0]]

The size of 
[[0 0 0]
 [0 0 0]
 [0 0 0]] will be 9

The shape of 
[[0 0 0]
 [0 0 0]
 [0 0 0]] is (3, 3)


## Q-6: Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing diagonally and other element will be 0]

In [58]:
import numpy as np

arr_mat = np.eye(5)
print(arr_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
identity_matrix = np.identity(5, dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [61]:
mat_diag = np.diag([1,1,1,1,1])
print(mat_diag)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
