In [ ]:
#Numpy - Array Manipulation.

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10 , (3,4))

In [ ]:
arr

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

In [ ]:
arr.reshape(6,2)

array([[4, 4],
       [8, 6],
       [8, 2],
       [5, 8],
       [5, 2],
       [8, 9]])

In [ ]:
arr.reshape(2,6)

array([[4, 4, 8, 6, 8, 2],
       [5, 8, 5, 2, 8, 9]])

In [ ]:
arr.reshape(2,-242342)

array([[4, 4, 8, 6, 8, 2],
       [5, 8, 5, 2, 8, 9]])

In [ ]:
arr.T

array([[4, 8, 5],
       [4, 2, 2],
       [8, 5, 8],
       [6, 8, 9]])

In [ ]:
arr

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

In [ ]:
arr.flatten()

array([4, 4, 8, 6, 8, 2, 5, 8, 5, 2, 8, 9])

In [ ]:
arr1 = np.array([1,2,3,3,4])

In [ ]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [ ]:
arr

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

In [ ]:
np.squeeze(arr)

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

In [ ]:
data = np.array([[1] , [2] , [3]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
#Numpy - Binary Operators.

In [ ]:
arr1 = np.random.randint(1,10 , (3,4))

In [ ]:
arr2 = np.random.randint(1,10 , (3,4))

In [ ]:
arr1

array([[7, 9, 2, 2],
       [1, 2, 8, 2],
       [7, 5, 4, 6]])

In [ ]:
arr2

array([[2, 8, 7, 5],
       [8, 2, 6, 9],
       [1, 8, 4, 3]])

In [ ]:
arr1+arr2

array([[ 9, 17,  9,  7],
       [ 9,  4, 14, 11],
       [ 8, 13,  8,  9]])

In [ ]:
arr1*arr2

array([[14, 72, 14, 10],
       [ 8,  4, 48, 18],
       [ 7, 40, 16, 18]])

In [ ]:
arr1/arr2

array([[3.5       , 1.125     , 0.28571429, 0.4       ],
       [0.125     , 1.        , 1.33333333, 0.22222222],
       [7.        , 0.625     , 1.        , 2.        ]])

In [ ]:
arr1-arr2

array([[ 5,  1, -5, -3],
       [-7,  0,  2, -7],
       [ 6, -3,  0,  3]])

In [ ]:
arr1%arr2

array([[1, 1, 2, 2],
       [1, 0, 2, 2],
       [0, 5, 0, 0]])

In [ ]:
arr1 ** arr2

array([[      49, 43046721,      128,       32],
       [       1,        4,   262144,      512],
       [       7,   390625,      256,      216]])

In [ ]:
arr1 & arr2

array([[2, 8, 2, 0],
       [0, 2, 0, 0],
       [1, 0, 4, 2]])

In [ ]:
arr1

array([[7, 9, 2, 2],
       [1, 2, 8, 2],
       [7, 5, 4, 6]])

In [ ]:
arr2

array([[2, 8, 7, 5],
       [8, 2, 6, 9],
       [1, 8, 4, 3]])

In [ ]:
~arr1

array([[ -8, -10,  -3,  -3],
       [ -2,  -3,  -9,  -3],
       [ -8,  -6,  -5,  -7]])

In [ ]:
arr1|arr2

array([[ 7,  9,  7,  7],
       [ 9,  2, 14, 11],
       [ 7, 13,  4,  7]])

In [ ]:
arr1>arr2

array([[ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False,  True]])

In [ ]:
#Numpy - String Functions.

In [ ]:
arr = np.array(['sudh' , "Kumar"])

In [ ]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [ ]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
#Numpy - Mathematical Functions.

In [ ]:
arr1

array([[7, 9, 2, 2],
       [1, 2, 8, 2],
       [7, 5, 4, 6]])

In [ ]:
np.sin(arr1)

array([[ 0.6569866 ,  0.41211849,  0.90929743,  0.90929743],
       [ 0.84147098,  0.90929743,  0.98935825,  0.90929743],
       [ 0.6569866 , -0.95892427, -0.7568025 , -0.2794155 ]])

In [ ]:
np.cos(arr1)

array([[ 0.75390225, -0.91113026, -0.41614684, -0.41614684],
       [ 0.54030231, -0.41614684, -0.14550003, -0.41614684],
       [ 0.75390225,  0.28366219, -0.65364362,  0.96017029]])

In [ ]:
np.tan(arr1)

array([[ 0.87144798, -0.45231566, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986, -6.79971146, -2.18503986],
       [ 0.87144798, -3.38051501,  1.15782128, -0.29100619]])

In [ ]:
np.tanh(arr1)

array([[0.99999834, 0.99999997, 0.96402758, 0.96402758],
       [0.76159416, 0.96402758, 0.99999977, 0.96402758],
       [0.99999834, 0.9999092 , 0.9993293 , 0.99998771]])

In [ ]:
np.log10(arr1)

array([[0.84509804, 0.95424251, 0.30103   , 0.30103   ],
       [0.        , 0.30103   , 0.90308999, 0.30103   ],
       [0.84509804, 0.69897   , 0.60205999, 0.77815125]])

In [ ]:
np.exp(arr1)

array([[1.09663316e+03, 8.10308393e+03, 7.38905610e+00, 7.38905610e+00],
       [2.71828183e+00, 7.38905610e+00, 2.98095799e+03, 7.38905610e+00],
       [1.09663316e+03, 1.48413159e+02, 5.45981500e+01, 4.03428793e+02]])

In [ ]:
np.sqrt(arr1)

array([[2.64575131, 3.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 2.82842712, 1.41421356],
       [2.64575131, 2.23606798, 2.        , 2.44948974]])

In [ ]:
np.power(arr1,2)

array([[49, 81,  4,  4],
       [ 1,  4, 64,  4],
       [49, 25, 16, 36]])

In [ ]:
np.mean(arr1)

4.583333333333333

In [ ]:
np.median(arr1)

4.5

In [ ]:
np.std(arr1)

2.6601482832520613

In [ ]:
np.var(arr1)

7.076388888888888

In [ ]:
np.min(arr1
      )

1

In [ ]:
np.max(arr1)

9